### ISSUE TITLE
What's the copyright/license for the content of the site?

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/space-journalism-handbook#4]

**Comment by esagara** [comment]
Can we close this?

**Comment by mikejcorey** [comment]
Yes.

On Sep 27, 2017 4:45 PM, "Eric Sagara" <notifications@github.com> wrote:

Can we close this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cirlabs/space-journalism-handbook/issues/4#issuecomment-332686641>,
or mute the thread
